### ISSUE TITLE
Add test for image blit with buffer format 6

### ISSUE THREAD

**Issue by abaire** [abaire/nxdk_pgraph_tests#3]
See https://github.com/mborgerson/xemu/issues/324 - Blade 2 uses ~~op mode 6, which seems like it might be a premultiplied blend~~ surface format 0x06 which looks like XRGB -> ZRGB.

**Comment by Triticum0** [comment]
Issue should be renamed after your recent findings

**Comment by abaire** [comment]
Fixed by 70671571bc242aaff493e2454c6c31cf21380507
