### ISSUE TITLE
Fallback output path should not assume F partition exists

### ISSUE THREAD

**Issue by mborgerson** [abaire/nxdk_pgraph_tests#59]
Running from disc image with conventional HDD drive layout (no F partition), tester will fail when trying to create output directory because it assumes F partition exists. I think a using E:\, perhaps in udata, would make sense.

https://github.com/abaire/nxdk_pgraph_tests/blob/a2d65cba77e87d1c19597ac793e5b62edf34649a/src/main.cpp#L52

**Comment by abaire** [comment]
Agreed; at the moment there's a build flag to configure the fallback path but it'd be better to have a safe default that can be overridden to something situational than the inverse case we're in now.

**Comment by abaire** [comment]
For posterity, I decided to just use just e: as in the devkit case `UDATA` isn't a child of the default e: mount (which is actually `e:\devkit`, a sibling of `UDATA`).
