### ISSUE TITLE
CreateSurfaceWithSquareOffset4 Crashes xemu

### ISSUE THREAD

**Issue by Triticum0** [abaire/nxdk_pgraph_tests#86]
When using automatic testing the test crashes with this assertion line 5970 (suface -> pitch * height <=dma.limit + 1) on CreateSurfaceWithSquareOffset4

**Comment by abaire** [comment]
This one is expected, there's an outstanding PR in xemu that will fix it. 

In general there are very often tests that crash xemu, unless they also crash hardware they should not be reported here (and it's almost always certain that I either have a fix for xemu in an outstanding PR or am actively working on a fix).
