### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by antangelo** [abaire/nxdk_pgraph_tests#92]
There is currently no license file or information (that I could find) in the tester's source tree, would be nice to have some clarity on how the project is licensed

**Comment by abaire** [comment]
The initial code was based on a branch in the nxdk from @ernegien pre-license cleanup, so it's unclear what license would be applicable (the README for https://github.com/Ernegien/nxdk/tree/test/texture-formats would apply).

I generally use CC0 1.0 Universal for my work, but following BSD or MIT to align with the nxdk at the time that I forked the texture-formats test seems most reasonable to me. Ideally we can just use MIT to stay aligned with the current licensing (https://github.com/XboxDev/nxdk/tree/master/LICENSES).

Assuming @ernegien can clarify the license for the original code and that it would likely be one 
@abairmj - would you be OK with MIT licensing for your contributions?

@antangelo - would you be OK with MIT licensing for your contributions?

@NZJenkins - would you be OK with MIT licensing for your contributions?

@mborgerson - would you be OK with MIT licensing for your contributions?

@Metalsasi - would you be OK with MIT licensing for your contributions?

**Comment by Ernegien** [comment]
Good to see you abaire :) I typically go with MIT but anything I produce that's Xbox-related I'm also fine re-licensing to whatever.

**Comment by abairmj** [comment]
Good to hear from you bro!  I'm fine with MIT or any other license.

**Comment by mborgerson** [comment]
MIT is fine with me, thanks

**Comment by antangelo** [comment]
I'm good with MIT for my contributions

**Comment by Metalsasi** [comment]
Hi, I am also fine with MIT license.
